# Lösungen zu den Übungsaufgaben {#sec-exercise-solutions}

\addtocontents{toc}{\protect\setcounter{tocdepth}{0}}

```{r}
#| include: false

source("_common.R")
```

## Kapitel 1 {#sec-exercise-solutions-01 .unlisted}

::: exercises-solution
{{< include exercises/_01-sa-data-hello.qmd >}}
:::

## Kapitel 2 {#sec-exercise-solutions-02 .unlisted}

::: exercises-solution
{{< include exercises/_02-sa-data-design.qmd >}}
:::

## Kapitel 3 {#sec-exercise-solutions-03 .unlisted}

Anwendungskapitel, keine Übungsaufgaben.

## Kapitel 4 {#sec-exercise-solutions-04 .unlisted}

::: exercises-solution
{{< include exercises/_04-sa-explore-categorical.qmd >}}
:::

## Kapitel 5 {#sec-exercise-solutions-05 .unlisted}

::: exercises-solution
{{< include exercises/_05-sa-explore-numerical.qmd >}}
:::

## Kapitel 6 {#sec-exercise-solutions-06 .unlisted}

Anwendungskapitel, keine Übungsaufgaben.

## Kapitel 7 {#sec-exercise-solutions-07 .unlisted}

::: exercises-solution
{{< include exercises/_07-sa-model-slr.qmd >}}
:::

## Kapitel 8 {#sec-exercise-solutions-08 .unlisted}

::: exercises-solution
{{< include exercises/_08-sa-model-mlr.qmd >}}
:::

## Kapitel 9 {#sec-exercise-solutions-09 .unlisted}

::: exercises-solution
{{< include exercises/_09-sa-model-logistic.qmd >}}
:::

## Kapitel 10 {#sec-exercise-solutions-10 .unlisted}

Anwendungskapitel, keine Übungsaufgaben.

## Kapitel 11 {#sec-exercise-solutions-11 .unlisted}

::: exercises-solution
{{< include exercises/_11-sa-foundations-randomization.qmd >}}
:::

## Kapitel 12 {#sec-exercise-solutions-12 .unlisted}

::: exercises-solution
{{< include exercises/_12-sa-foundations-bootstrapping.qmd >}}
:::

## Kapitel 13 {#sec-exercise-solutions-13 .unlisted}

::: exercises-solution
{{< include exercises/_13-sa-foundations-mathematical.qmd >}}
:::

## Kapitel 14 {#sec-exercise-solutions-14 .unlisted}

::: exercises-solution
{{< include exercises/_14-sa-foundations-errors.qmd >}}
:::

## Kapitel 15 {#sec-exercise-solutions-15 .unlisted}

Anwendungskapitel, keine Übungsaufgaben.

## Kapitel 16 {#sec-exercise-solutions-16 .unlisted}

::: exercises-solution
{{< include exercises/_16-sa-inference-one-prop.qmd >}}
:::

## Kapitel 17 {#sec-exercise-solutions-17 .unlisted}

::: exercises-solution
{{< include exercises/_17-sa-inference-two-props.qmd >}}
:::

## Kapitel 18 {#sec-exercise-solutions-18 .unlisted}

::: exercises-solution
{{< include exercises/_18-sa-inference-tables.qmd >}}
:::

## Kapitel 19 {#sec-exercise-solutions-19 .unlisted}

::: exercises-solution
{{< include exercises/_19-sa-inference-one-mean.qmd >}}
:::

## Kapitel 20 {#sec-exercise-solutions-20 .unlisted}

::: exercises-solution
{{< include exercises/_20-sa-inference-two-means.qmd >}}
:::

## Kapitel 21 {#sec-exercise-solutions-21 .unlisted}

::: exercises-solution
{{< include exercises/_21-sa-inference-paired-means.qmd >}}
:::

## Kapitel 22 {#sec-exercise-solutions-22 .unlisted}

::: exercises-solution
{{< include exercises/_22-sa-inference-many-means.qmd >}}
:::

## Kapitel 23 {#sec-exercise-solutions-23 .unlisted}

Anwendungskapitel, keine Übungsaufgaben.

## Kapitel 24 {#sec-exercise-solutions-24 .unlisted}

::: exercises-solution
{{< include exercises/_24-sa-inf-model-slr.qmd >}}
:::

## Kapitel 25 {#sec-exercise-solutions-25 .unlisted}

::: exercises-solution
{{< include exercises/_25-sa-inf-model-mlr.qmd >}}
:::

## Kapitel 26 {#sec-exercise-solutions-26 .unlisted}

::: exercises-solution
{{< include exercises/_26-sa-inf-model-logistic.qmd >}}
:::

