# Explorative Datenanalyse {#sec-explore .unnumbered}

Nach dem Erhalt eines Datensatzes ist es äußerst wichtig, die Eigenschaften der vorhandenen Daten zu verstehen. Manchmal ist der effektivste Weg, die Daten zu begreifen, die Betrachtung von Zusammenfassungsstatistiken oder anderen numerischen Maßen. Oft ist es jedoch ein Bild, das mehr sagt als tausend Worte. Zu wissen, wie man die zugrundeliegende Bedeutung in einem Datensatz am besten vermittelt, ist ein äußerst wichtiger Aspekt der Kommunikation von Ergebnissen.

- Kategoriale Daten stehen im Mittelpunkt von [Chapter -@sec-explore-categorical]. Sowohl numerische als auch grafische Zusammenfassungen werden als Möglichkeiten vorgestellt, Informationen über kategoriale Daten zu vermitteln.
- Numerische Daten stehen im Mittelpunkt von [Chapter -@sec-explore-numerical]. Sowohl numerische als auch grafische Zusammenfassungen werden als Möglichkeiten vorgestellt, Informationen über numerische Daten zu vermitteln.
- [Chapter -@sec-explore-applications] geht vertieft auf wichtige Überlegungen bei der Erstellung einer Visualisierung ein.

Obwohl unser Buch softwareunabhängig ist, ist eine der besten Möglichkeiten, sich mit numerischen und grafischen Zusammenfassungen vertraut zu machen, das Üben mit verschiedenen Datensätzen mithilfe von Statistiksoftware. Wenn Sie beispielsweise R verwenden möchten, könnten Sie einige der Kapitel in [R for Data Science](https://r4ds.hadley.nz/) (https://r4ds.hadley.nz) durcharbeiten, insbesondere die Teile [Whole game](https://r4ds.hadley.nz/whole-game) und [Visualize](https://r4ds.hadley.nz/visualize).
