# Grundlagen der Inferenz {#sec-foundations .unnumbered}

Zu den zentralen Konzepten der Statistik gehört das Ziehen von Schlussfolgerungen über eine Grundgesamtheit anhand von Informationen in einer Stichprobe; dieser Prozess wird als statistische Inferenz bezeichnet. Durch den Einsatz von computergestützten Methoden sowie einer gut entwickelten mathematischen Theorie können wir verstehen, wie sich ein Datensatz von einem anderen unterscheidet – selbst wenn die beiden Datensätze unter identischen Bedingungen erhoben wurden. In diesem Teil werden wir die zentralen Konzepte und Begriffe durcharbeiten, die in späteren Kapiteln expliziter angewendet werden.

- [Chapter -@sec-foundations-randomization] beschreibt die Randomisierung, bei der Beobachtungen wiederholt permutiert werden, um Szenarien darzustellen, in denen es keine Assoziation zwischen zwei interessierenden Variablen gibt.
- [Chapter -@sec-foundations-bootstrapping] beschreibt das Bootstrapping, bei dem wiederholt (mit Zurücklegen) aus den beobachteten Daten gezogen wird, um viele Stichproben zu erzeugen, die den Originaldaten ähnlich, aber nicht identisch sind.
- [Chapter -@sec-foundations-mathematical] führt den Zentralen Grenzwertsatz ein, der eine theoretische mathematische Annäherung an die durch Randomisierung und Bootstrapping beobachtete Variabilität in den Daten darstellt.
- In [Chapter -@sec-foundations-decision-errors] wird Ihnen eine Struktur zur Beschreibung vorgestellt, wann und wie Fehler innerhalb der statistischen Inferenz auftreten können.
- [Chapter -@sec-foundations-applications] enthält eine Anwendung zur Fallstudie „Malaria-Impfstoff", in der die Themen aus diesem Teil des Buches vollständig entwickelt werden.

Obwohl computergestützte und mathematische Methoden häufig beide geeignet sind (und ähnliche Ergebnisse liefern), sollte Ihnen das Studium beider Ansätze davon überzeugen, dass (1) es fast nie einen einzigen „richtigen" Ansatz gibt, und (2) es verschiedene Möglichkeiten gibt, die von Datensatz zu Datensatz beobachtete Variabilität zu quantifizieren.
