# Inferenzielle Modellierung {#sec-inf-model .unnumbered}

In einem früheren Teil, [Regression modeling](https://openintro-ims2.netlify.app/regression-modeling), haben Sie gelernt, wie man lineare und logistische Regressionsmodelle auf der Grundlage eines Satzes von Beobachtungen erstellt.
In einem anderen Teil, [Foundations of inference](https://openintro-ims2.netlify.app/foundations-of-inference), haben Sie die Strukturen kennengelernt, die es uns ermöglichen, inferenzielle Aussagen über eine Grundgesamtheit auf der Grundlage einer Stichprobe von Daten zu treffen.
In diesem Teil entwickeln wir Inferenzmethoden, die auf Regressionsmodelle angewendet werden.

-   [Chapter -@sec-inf-model-slr] liefert spezifische Details zur Inferenz für lineare Regressionsmodelle mit einem einzigen Prädiktor.
-   [Chapter -@sec-inf-model-mlr] liefert spezifische Details zur Inferenz für lineare Regressionsmodelle mit mehreren Prädiktoren.
-   [Chapter -@sec-inf-model-logistic] liefert spezifische Details zur Inferenz für logistische Regressionsmodelle.
-   [Chapter -@sec-inf-model-applications] enthält eine Anwendung zur Fallstudie „Mario Kart", in der die Themen dieses Teils des Buches zur linearen Regression vollständig entwickelt werden.

Wir haben bislang nur an der Oberfläche der Informationen zu Modellierung und verwandten Inferenzmethoden gekratzt.
Wir hoffen, dass die behandelten Ideen Ihren Appetit geweckt haben, mehr über Modellierung auf höherem Niveau zu lernen.
