# Einführung in die Daten {.unnumbered}

Der erste Teil des Buches wird Sie in Daten, ihre Eigenschaften, die Art ihrer Erhebung und die Struktur des Studiendesigns einführen.
Unterschiedliche Daten und Rahmenbedingungen führen zu unterschiedlichen **Arten** von Schlussfolgerungen, daher sollten Sie stets die Herkunft der Daten im Blick behalten – insbesondere wenn Sie zu Modellierung und Inferenz übergehen.

-   In [Chapter -@sec-data-hello] werden Sie in aufgeräumte Daten (tidy data) eingeführt, eine wichtige Struktur zum Beschreiben, Visualisieren und Analysieren von Daten.

-   In [Chapter -@sec-data-design] liegt der Schwerpunkt auf dem Studiendesign.
    Insbesondere wird die entscheidende Unterscheidung zwischen Zufallsstichproben und Randomisierung herausgearbeitet.

-   [Chapter -@sec-data-applications] enthält eine Anwendung zur Fallstudie der Paralympics, in der die Themen aus dem Einführungsteil des Buches vollständig ausgearbeitet werden.

Wir empfehlen Ihnen, nach der Lektüre jedes neuen Teils des Lehrbuchs zu diesem grundlegenden Abschnitt zurückzukehren und ihn zu wiederholen.
Insbesondere lohnt es sich, @fig-randsampValloc in allen inferenziellen Kontexten zu betrachten, die Sie behandeln.
Jeder Datensatz, den Sie analysieren, wird einen etwas anderen Kontext haben, der eine sorgfältige Überlegung zu den geeigneten Schlussfolgerungen erfordert.
