# Vorwort {.unnumbered}

\vspace{-10mm}

Willkommen zur zweiten Ausgabe von „Introduction to Modern Statistics"!

Wir hoffen, dass die Leserinnen und Leser neben dem Aufbau eines Fundaments an statistischem Denken und statistischen Methoden drei Ideen aus diesem Buch mitnehmen werden.

1.  Statistik ist ein angewandtes Fachgebiet mit einem breiten Spektrum praktischer Anwendungen.
2.  Man muss kein Mathegenie sein, um aus interessanten, realen Daten zu lernen.
3.  Daten sind unordentlich und statistische Werkzeuge sind unvollkommen. Wenn man jedoch die Stärken und Schwächen dieser Werkzeuge versteht, kann man sie nutzen, um interessante Dinge über die Welt zu lernen.

## Überblick über das Lehrbuch {.unnumbered .unlisted}

-   **Teil 1: Einführung in die Daten.** Datenstrukturen, Variablen, Zusammenfassungen, Grafiken sowie grundlegende Techniken zur Datenerhebung und Studiengestaltung.
-   **Teil 2: Explorative Datenanalyse.** Datenvisualisierung und -zusammenfassung mit besonderem Schwerpunkt auf multivariaten Zusammenhängen.
-   **Teil 3: Regressionsmodellierung.** Modellierung numerischer und kategorialer Ergebnisse mit linearer und logistischer Regression sowie die Nutzung von Modellergebnissen zur Beschreibung von Zusammenhängen und zur Erstellung von Vorhersagen.
-   **Teil 4: Grundlagen der Inferenz.** Fallstudien werden verwendet, um die Ideen der statistischen Inferenz mit Randomisierungstests, Bootstrap-Intervallen und mathematischen Modellen einzuführen.
-   **Teil 5: Statistische Inferenz.** Weitere Details der statistischen Inferenz mittels Randomisierungstests, Bootstrap-Intervallen und mathematischen Modellen für numerische und kategoriale Daten.
-   **Teil 6: Inferenzielle Modellierung.** Erweiterung der bisher vorgestellten Inferenztechniken auf lineare und logistische Regressionsmodelle sowie Bewertung der Modellleistung.

Jeder Teil enthält mehrere Kapitel und endet mit einer Fallstudie.
Aufbauend auf den im Teil behandelten Inhalten bietet die Fallstudie einen Überblick auf hohem Niveau unter Verwendung der Werkzeuge und Techniken des jeweiligen Teils.

In den Kapiteln zur statistischen Inferenz haben wir eine parallele Struktur vorgestellt, die die Studierenden sowohl durch computergestützte als auch durch mathematische Ansätze zu jedem Inferenzthema führt.
Der Versuch, jeden Ansatz für jedes Thema abzudecken, würde für einen einsemestrigen Kurs wahrscheinlich zu viel Stoff ergeben.
Wir empfehlen, bewusste Entscheidungen bei der Führung der Studierenden durch das Buch zu treffen.
Einige mögliche Pfade durch das Buch (mit Kapitelnummern in Klammern) sind wie folgt:

* Schwerpunkt auf der **parallelen Struktur computergestützter und mathematischer Methoden**: Einführung in die Daten (1, 2), Explorative Datenanalyse (4, 5), Regression (7), Grundlagen (11, 12, 13, 14), Inferenz (eine Auswahl aus: 16, 17, 18, 19, 20, 21, 22; möglicherweise: 16, 17, 19, 20).
* Schwerpunkt auf **computergestützten Methoden**: Einführung in die Daten (1, 2), Explorative Datenanalyse (4, 5), Regression (7), Grundlagen (11, 12, 14), Inferenz (nur computergestützte Methoden für eine Auswahl aus: 16, 17, 18, 19, 20, 21, 22).
* Schwerpunkt auf **mathematischen Methoden**: Einführung in die Daten (1, 2), Explorative Datenanalyse (4, 5), Regression (7), Grundlagen (11, 12, 13, 14), Inferenz (nur mathematische Methoden für eine Auswahl aus: 16, 17, 18, 19, 20, 21, 22).
* Schwerpunkt auf **Modellierung**: Einführung in die Daten (1, 2), Explorative Datenanalyse (4, 5), Regression (7, 8, 9), Grundlagen (11, 12, 13, 14), Inferenz (19), Inferenzielle Modellierung (24, 25, 26).

Wir erwarten, dass die meisten Kurse nach einem klassischen Lehrplan keine Zeit haben werden, die Kapitel im letzten Teil, Inferenzielle Modellierung (24, 25, 26), zu behandeln.

\clearpage

Jedes Kapitel endet mit einer Wiederholung, die eine Kapitelzusammenfassung sowie eine Liste der im Kapitel eingeführten Schlüsselbegriffe enthält.
Wenn Sie nicht sicher sind, was einige dieser Begriffe bedeuten, empfehlen wir Ihnen, im Text zurückzugehen und deren Definitionen zu überprüfen.
Wir stellen sie absichtlich in alphabetischer Reihenfolge vor, statt in der Reihenfolge ihres Erscheinens, sodass sie etwas schwieriger zu finden sein werden.
Sie sollten sie jedoch leicht erkennen können, da sie als **fett gedruckter Text** hervorgehoben sind.

## Änderungen für die zweite Ausgabe {.unnumbered .unlisted}

Obwohl die zweite Ausgabe keine wesentliche Änderung gegenüber der [ersten Ausgabe](https://openintro-ims1.netlify.app/) darstellt, haben wir hart daran gearbeitet, Inhalte zu verbessern, Aufgaben hinzuzufügen und Text und Code zu aktualisieren, um Änderungen in bewährten Praktiken widerzuspiegeln (z. B. ist das Buch nun in [Quarto](https://quarto.org/) geschrieben).

Eine kurze Zusammenfassung der wichtigsten Änderungen folgt:

* Fünfundzwanzig völlig neue Aufgaben wurden hinzugefügt. Die meisten der neuen Aufgaben werden an bestehende Aufgaben angehängt, um eine ähnliche Nummerierung zwischen den Ausgaben beizubehalten. Einige Aufgaben wurden jedoch verschoben, um sowohl ungerade Aufgaben (mit Lösungen) als auch gerade Aufgaben (ohne Lösungen) zum gleichen Thema bereitzustellen.

* Mehrere Datensätze wurden hinzugefügt oder aktualisiert. Zum Beispiel können die [`pm25_2022_durham`](http://openintrostat.github.io/openintro/reference/pm25_2022_durham.html)-Daten zur Luftqualität in Durham, NC im Jahr 2022 im R-Paket [**openintro**](https://openintrostat.github.io/openintro/) gefunden werden.

* [Kapitel -@sec-data-applications] wurde mit einem aktualisierten Kontext und Datenbeispiel neu geschrieben. Zusätzlich untersuchen wir in [Kapitel -@sec-data-applications] das Simpsonsche Paradoxon.

* Im gesamten Text und in den Aufgaben wurde „statistically significant" in „statistically discernible" geändert, um uns vom umgangssprachlichen Gebrauch des Wortes „significant" zu distanzieren.

## Beispiele und Aufgaben {.unnumbered .unlisted}

Beispiele werden bereitgestellt, um ein Verständnis für die Anwendung von Methoden zu entwickeln.

::: {.workedexample data-latex=""}
Dies ist ein Beispiel.
Wenn hier eine Frage gestellt wird, wo kann die Antwort gefunden werden?

------------------------------------------------------------------------

Die Antwort kann hier gefunden werden, im Lösungsabschnitt des Beispiels!
:::

Wenn wir der Meinung sind, dass die Leserin oder der Leser bereit ist, eine Lösung selbst zu erarbeiten, formulieren wir dies als Geführte Übung.

::: {.guidedpractice data-latex=""}
Die Leserin oder der Leser kann die Antwort auf jede Geführte Übung überprüfen oder erlernen, indem sie oder er die vollständige Lösung in einer Fußnote nachschlägt.[^preface-1]
:::

[^preface-1]: Geführte Übungsaufgaben sollen Ihr Denken anregen, und Sie können sich selbst überprüfen, indem Sie die Fußnotenlösung zu jeder Geführten Übung nachschlagen.

Am Ende jedes Kapitels werden auch Aufgaben bereitgestellt.
Lösungen werden für ungerade nummerierte Aufgaben in [Anhang -@sec-exercise-solutions] angegeben.

\clearpage

## Datensätze und ihre Quellen {.unnumbered .unlisted}

Ein Großteil der im Buch verwendeten Datensätze kann in verschiedenen R-Paketen gefunden werden.
Jedes Mal, wenn ein neuer Datensatz in der Erzählung eingeführt wird, wird ein Verweis auf das Paket wie der folgende angegeben.
Viele dieser Datensätze befinden sich im R-Paket [**openintro**](http://openintrostat.github.io/openintro), das Datensätze enthält, die in den Open-Source-Lehrbüchern von [OpenIntro](https://www.openintro.org/) verwendet werden.[^preface-2]

[^preface-2]: Mine Çetinkaya-Rundel and David Diez and Andrew Bray and Albert Y. Kim and Ben Baumer and Chester Ismay and Nick Paterno and Christopher Barr (2024).
    openintro: Datasets and Supplemental Functions from 'OpenIntro' Textbooks and Labs.
    R package version 2.5.0.
    <https://github.com/openintrostat/openintro>.

::: {.data data-latex=""}
Die [`textbooks`](http://openintrostat.github.io/openintro/reference/textbooks.html)-Daten können im R-Paket [**openintro**](http://openintrostat.github.io/openintro) gefunden werden.
:::

Die im Buch verwendeten Datensätze stammen aus echten Quellen wie Meinungsumfragen und wissenschaftlichen Artikeln, mit Ausnahme einiger weniger Fälle, in denen wir Beispieldaten verwenden, um ein bestimmtes Merkmal hervorzuheben oder ein bestimmtes Konzept zu erklären.
Quellenangaben für die echten Daten finden sich am Ende des Buches.

## Rechnen mit R {.unnumbered .unlisted}

Die Erzählung und die Aufgaben im Buch sind sprachagnostisch in Bezug auf Programmiersprachen; es ist jedoch zwar möglich, moderne Statistik ohne Computing zu erlernen, aber nicht möglich, sie anzuwenden.
Daher laden wir Sie ein, die in jedem Teil erlernten Konzepte mithilfe der interaktiven R-Tutorials und der R-Labore zu erkunden, die am Ende jedes Teils enthalten sind.

### Interaktive R-Tutorials {.unnumbered .unlisted}

Die selbstgesteuerten und interaktiven R-Tutorials wurden mit dem R-Paket [learnr](https://rstudio.github.io/learnr/index.html) entwickelt, und für deren Durchführung wird nur ein Internetbrowser benötigt.

::: {.alltutorials data-latex=""}
Jeder Teil wird mit einem Tutorial geliefert, das aus 4–10 Lektionen besteht und wie folgt aufgelistet ist.
:::

::: {.singletutorial data-latex=""}
Jede dieser Lektionen ist wie folgt aufgelistet.
:::

::: {.content-visible when-format="pdf"}
Sie können auf die vollständige Liste der Tutorials, die dieses Buch unterstützen, unter <https://openintrostat.github.io/ims-tutorials> zugreifen.
:::

::: {.content-visible when-format="html"}
Sie können auf die vollständige Liste der Tutorials, die dieses Buch unterstützen, [hier](https://openintrostat.github.io/ims-tutorials) zugreifen.
:::

### R-Labore {.unnumbered .unlisted}

Sobald Sie sich mit dem Material in den Tutorials vertraut gemacht haben, empfehlen wir Ihnen auch, das Gelernte über die computergestützten Labore anzuwenden, die ebenfalls am Ende jedes Teils verlinkt sind.
Die Labore bestehen aus Fallstudien zur Datenanalyse und erfordern Zugang zu [R](https://cran.r-project.org/) und [RStudio](https://posit.co/products/open-source/rstudio/).
Das erste Labor enthält Installationsanweisungen.
Wenn Sie die Software lieber nicht lokal installieren möchten, können Sie auch [Posit Cloud](https://posit.cloud/) kostenlos ausprobieren.

::: {.singlelab data-latex=""}
Labore für jeden Teil sind wie folgt aufgelistet.
:::

::: {.content-hidden unless-format="pdf"}
Sie können auf die vollständige Liste der Labore, die dieses Buch unterstützen, unter [openintro.org/go?id=ims-r-labs](https://www.openintro.org/go?id=ims-r-labs) zugreifen.
:::

::: {.content-visible when-format="html"}
Sie können auf die vollständige Liste der Labore, die dieses Buch unterstützen, [hier](https://www.openintro.org/go?id=ims-r-labs) zugreifen.
:::

\clearpage

## OpenIntro, Online-Ressourcen und Mitmachen {.unnumbered .unlisted}

OpenIntro ist eine Organisation, die sich auf die Entwicklung kostenloser und erschwinglicher Bildungsmaterialien konzentriert. Wir ermutigen alle, die Statistik erlernen oder lehren, [openintro.org](http://www.openintro.org) zu besuchen und sich zu engagieren.

Alle OpenIntro-Ressourcen sind kostenlos, und jede und jeder ist willkommen, diese Online-Werkzeuge und Ressourcen mit oder ohne dieses Lehrbuch als Begleitung zu nutzen.

Wir schätzen Ihr Feedback.
Wenn es einen Teil des Projekts gibt, den Sie besonders mögen oder der Ihrer Meinung nach verbessert werden sollte, möchten wir von Ihnen hören.
Für Feedback zu diesem spezifischen Buch können Sie ein Issue im GitHub-Repository des Buches unter [github.com/openintrostat/ims](https://github.com/openintrostat/ims) öffnen.
Sie können auch Feedback zu diesem Buch oder einer anderen OpenIntro-Ressource über unser Kontaktformular unter [openintro.org](https://www.openintro.org/form/?f=contact) geben.

## Danksagungen {.unnumbered .unlisted}

Das *OpenIntro*-Projekt wäre ohne den Einsatz und die freiwilligen Stunden aller Beteiligten nicht möglich gewesen, und wir hoffen, dass Sie sich uns anschließen, um allen, die sich freiwillig bei OpenIntro engagieren, ein herzliches *Dankeschön* auszusprechen.

Die Autoren möchten den folgenden Personen danken:

-   David Diez und Christopher Barr für ihre Arbeit an der 1. Ausgabe dieses Buches,
-   Ben Baumer und Andrew Bray für ihren Beitrag zur Neugestaltung der Art und Reihenfolge, in der wir dieses Material präsentieren, sowie ihre Arbeit als ursprüngliche Autoren der interaktiven Tutorial-Inhalte,
-   Yanina Bellini Saibene, Florencia D'Andrea und Roxana Noelia Villafañe für ihre Arbeit bei der Erstellung der interaktiven Tutorials in learnr,
-   Peter Baumgartner für die Überprüfung und Überarbeitung der interaktiven learnr-Tutorials,
-   Will Gray für konzeptionelle Diagramme,
-   Allison Theobold, Melinda Yager und Randy Prium für ihr wertvolles Feedback und ihre Überprüfung des Buches,
-   Colin Rundel für Feedback zu den Inhalten und technische Hilfe bei der Konvertierung von LaTeX zu R Markdown,
-   Christophe Dervieux für Hilfe bei Multi-Output-bookdown-Problemen, und
-   Müge Çetinkaya und Meenal Patel für ihre gestalterische Vision.

Wir möchten auch den Entwicklern der Open-Source-Tools danken, die die Entwicklung und das Verfassen dieses Buches ermöglichen, z. B. [Quarto](https://quarto.org/), [tidyverse](https://tidyverse.org/), [tidymodels](https://tidymodels.org/) und [icons8](http://icons8.com/).

Wir sind auch den vielen Lehrenden, Studierenden und anderen Lesenden dankbar, die dazu beigetragen haben, OpenIntro-Ressourcen durch ihr Feedback zu verbessern.
