# Regressionsmodellierung {#sec-model .unnumbered}

Zu den am häufigsten verwendeten Methoden zur Modellierung einer Zielvariablen in Abhängigkeit von einer oder mehreren Prädiktorvariablen gehört die Regression. Die lineare Regression wird am häufigsten verwendet, wenn die Zielvariable numerisch (und noch besser, stetig) ist; die logistische Regression wird verwendet, wenn die Zielvariable binär ist.

- In [Chapter -@sec-model-slr] werden Sie in das Finden einer bestmöglichen Ausgleichsgeraden mithilfe der Methode der kleinsten Quadrate eingeführt. Zusätzlich werden die Korrelation und das Bestimmtheitsmaß als Möglichkeit zur Beschreibung der Stärke des linearen Modells vorgestellt.
- In [Chapter -@sec-model-mlr] wird das lineare Modell erweitert, um mehrere Prädiktorvariablen in einem einzigen Modell zu berücksichtigen. Wir erörtern die Vorteile sowie die Fallstricke, die beim Einsatz mehrerer Prädiktoren auftreten können.
- In [Chapter -@sec-model-logistic] ist die Zielvariable auf binäre Werte beschränkt, was die gesamte Struktur verändert und das logistische Regressionsmodell ergibt. Die Gemeinsamkeiten zwischen den Regressionsmodellen (nämlich lineare Kombinationen der Prädiktoren) werden dargestellt. Zusätzlich sehen Sie, dass die Vorhersagen der logistischen Regression nun Wahrscheinlichkeiten sind.
- [Chapter -@sec-model-application] enthält eine Anwendung zur Fallstudie „Häuser zum Verkauf", in der die Themen aus diesem Teil des Buches vollständig entwickelt werden.

Im späteren Teil des Lehrbuchs, im Teil [Inferential modeling](https://openintro-ims2.netlify.app/inferential-modeling), werden wir untersuchen, ob ein auf einer Stichprobe aufgebautes Regressionsmodell eine bestimmte Grundgesamtheit von Interesse beschreibt oder nicht.