# Statistische Inferenz {#sec-inference .unnumbered}

Während der vorherige Teil des Lehrbuchs, [Foundations of inference](https://openintro-ims2.netlify.app/foundations-of-inference), den Kern der statistischen Inferenz einführt, liefert dieser Teil Details zur Anwendung der statistischen Inferenz in bestimmten Situationen.
Das Verständnis der spezifischen Besonderheiten der verschiedenen Inferenzmethoden kann bei der Kommunikation der resultierenden Analysen hilfreich sein.

-   [Chapter -@sec-inference-one-prop] liefert spezifische Details zur Inferenz für einen einzelnen Anteilswert.

-   [Chapter -@sec-inference-two-props] liefert spezifische Details zur Inferenz beim Vergleich zweier Anteilswerte.

-   [Chapter -@sec-inference-tables] liefert spezifische Details zur Inferenz für Kontingenztabellen.

-   [Chapter -@sec-inference-one-mean] liefert spezifische Details zur Inferenz für einen einzelnen Mittelwert.

-   [Chapter -@sec-inference-two-means] liefert spezifische Details zur Inferenz beim Vergleich zweier unabhängiger Mittelwerte.

-   [Chapter -@sec-inference-paired-means] liefert spezifische Details zur Inferenz beim Vergleich gepaarter Mittelwerte.

-   [Chapter -@sec-inference-many-means] liefert spezifische Details zur Inferenz beim Vergleich vieler Mittelwerte.

-   [Chapter -@sec-inference-applications] enthält eine Anwendung zur Fallstudie „Redundante Adjektive", in der die Themen dieses Teils des Buches zu Mittelwerten vollständig entwickelt werden.

Nach dem Durcharbeiten der Details in diesem Teil sollten Sie ein gutes Gespür dafür haben, wie Inferenzmethoden sich ähneln und unterscheiden, wenn sie auf verschiedene Datenstrukturen angewendet werden.
Darüber hinaus sollten Sie in der Lage sein, sowohl computergestützte Methoden als auch mathematische Techniken auf das jeweilige Inferenzproblem anzuwenden.
